spyder-ide/qtawesome

QtAwesome/QtAwesome.py
QtAwesome/__init__.py
QtAwesome/fa.py
QtAwesome/iconic_font.py
example.py

Separated font-awesome specific things from general font-based icons.

Some cleanup in PyQtAwesome

---

QtAwesome/__init__.py
QtAwesome/iconic_font.py
example.py

Using the `icon_stack` function

Allow stacking font icons

---

QtAwesome/iconic_font.py
example.py

Support offset and opacity

---

qtawesome/iconic_font.py
setup.py

Corrections for Python 3 compatibility, adding some keywords. Adding `six` as a dependency.

Python 3 compat and keywords

---

example.py

This should give us the travis-ci result.

Use six in example

---

README.rst

basic change to test travis

---

example.py

Fix qt5 build issues

---

qtawesome/iconic_font.py

Fixes https://github.com/spyder-ide/spyder/issues/2597.

Fix osx ttf font loading

---

qtawesome/__init__.py
qtawesome/_version.py
setup.py

The version used by setup.py is now read in a slightly cleaner way.

Read version with exec

---

.travis.yml
example.py

Fix tests for PyQt5 and add Python 3.5 to the testing matrix

---

example.py

Using `app.setAttribute(Qt.AA_UseHighDpiPixmaps)`, which only exists with PyQt5.

Use high DPI pixmaps

---

MANIFEST.in

Future tarballs would now include the Sphinx documentation and makefiles and the project's LICENSE file. I have added the CHANGELOG.md and README.md, which are desirable for packaging in Linux distributions.
Closes #51

Update manifest template

---

README.md

PR: Update AppVeyor badge because of move to org account

---

MANIFEST.in

The script is needed for testing purposes on the packaging side.

PR: Include example script into tarball to run tests when the package is installed

---

qtawesome/animation.py

Fixes https://github.com/spyder-ide/qtawesome/issues/76

PR: Fix error when updating animations

---

.gitignore

PR: Ignore PyDev project files

---

README.md
docs/source/usage.rst

Replace QtGui by QtWidgets in `README.md` and `usage.rst`

PR: Replace QtGui by QtWidgets in docs

---

README.md

And also other minor improvements.

PR: Improve sponsors section in readme

---

qtawesome/iconic_font.py

Fixes https://github.com/spyder-ide/qtawesome/issues/125

PR: Fix file lock

---

qtawesome/iconic_font.py

PR: Remove warning for Python 2.7

---

qtawesome/icon_browser.py

PR: Fix deprecation warnings due to invalid escape sequences.

---

qtawesome/icon_browser.py

PR: Cast tileWidth to an integer (closes #162)

---

qtawesome/iconic_font.py

PR: Add DeprecationWarning for FontAwesome 4.7 icon set

---

.github/workflows/linux-tests.yml
.github/workflows/macos-tests.yml
.github/workflows/windows-tests.yml
README.md
setup.py

PR: Drop Python 3.6 support

---

qtawesome/iconic_font.py

PR: Handle per user font installation failing due to missing/not available registry keys

---

qtawesome/__init__.py
qtawesome/iconic_font.py
qtawesome/tests/test_qtawesome.py
setup.py

PR: Add logic to install bundled fonts system wide on Windows

---

.github/workflows/windows-tests.yml
example.py
qtawesome/animation.py

PR: Revert Qt binging conditional to run `example.py` and fix animations start/stop logic (CI)

---

SECURITY.md

Add new standard security policy for QtAwesome

PR: Add new security policy
