QtAwesome/__init__.py, QtAwesome/animation.py, QtAwesome/iconic_font.py, example.py
This is separating animations in their own files, and slightly changing the API for setting animations. 
Besides default values, `Spin` and `Pulse` seem to be doing the same thing, so I will refactor in next commit unless I missed something. 
I don't like that animations require the parent widget when creating them, I think that this should dynamically grab it when painting. Looking at it.
=> Animation objects

README.rst
I don't know why you selected camel case for the project name on PyPi, etc, (I really don't like it) but @SylvainCorlay agreed with a lower case name for the repo ;-)
=> Fix Travis url in README

conda.recipe/build.sh, conda.recipe/meta.yaml
Some notes to @SylvainCorlay and @goanpeca:
1. I decided to remove Qtawesome from Spyder source tree (see spyder-ide/spyder#2831) because Qtawesome depends on six while Spyder doesn't. That's a hidden dependency problem that can be fixed by making Qtawesome a proper Spyder dep (which is my plan in 2831).
2. That's why I need a conda package for Qtawesome :-)
2. Please do a new release of Qtawesome to account for the problems you fixed in OS X. I made the current recipe to depend on the commit where PR #27 was merged, but it'd be nicer to just have a new release.
3. Please tag your releases :-) There's not a single tag in this repo!
=> Add a conda recipe to the tree

RELEASE.md, qtawesome/_version.py
@ccordoba12 streamlining release process for qtawesome.
I also added tags for the past versions, from `0.1.5`. I don't think that earlier versions have much interest.
=> Adding release instruction and setting current version to dev

conda.recipe/build.sh, conda.recipe/meta.yaml
This is a little trick I learned from the Anaconda team: by using
python setup.py install --single-version-externally-managed --root=/
we avoid `setuptools` to install or look for runtime dependencies for a package when conda is **building** it.
So this avoids using runtime deps as build deps too in our conda recipe, when the only build deps for `qtawesome` are `python` and `setuptools`.
=> Conda recipe: Remove unneeded build dependencies

.ciocheck, README.md, circle.yml
Fixes #53 
---
This add ciocheck as a tool for checking format/autoformating and running tests
More info at [ciocheck](https://github.com/ContinuumIO/ciocheck/)
Also add circle ci integration for running linux tests, will then change travis to make mac tests.
@SylvainCorlay any comments?
=> PR: Add ciocheck and circle ci linux integration

qtawesome/iconic_font.py
This is part of an effort to improve the management of errors that cause a Spyder crash when trying to load fonts from the `.ttf` files in the fonts directory and these are corrupt.
=> PR: Add validation to raise exception when fonts are empty or corrupt

.ciocheck, qtawesome/iconic_font.py
This verifies that fonts are not empty and/or missing before checking their hashes.
=> Improve verification that our fonts are not empty and/or missing

qtawesome/iconic_font.py
Fixes #64.
----
This is needed for Linux packagers that want to use system fonts.
=> PR: Add a way to not verify hash of vendorized fonts

qtawesome/iconic_font.py
PySide2 misses que qRound method. It can be simply replaced by the Python built-in round.
=> PR: Replace qRound (missing in PySide2) with round

docs/environment.yml
Should fix the ReadTheDocs builds that have been broken for a while:
https://readthedocs.org/projects/qtawesome/builds/8159001/
=> PR: Fix bad package dependency in docs/environment.yml

MANIFEST.in
Without this conda can't create packages for QtAwesome.
=> PR: Add setupbase.py to our tarball

setupbase.py
In an effort to prevent further mistakes, I took the core code from https://github.com/chrissimpkins/fontname.py and made it into a utility function that then renames "regular" and "solid" flavours of FA5 to prevent issues like #107 .
This means that the command technically introduces a requirement for the "fonttools" module. Since it is a "dev" command I did not include it in the setup.py's `install_requires` but I did a lot of reading and it seems very tricky to declare the dependency for the command only. There's an `extra_requires` thing but that only works for package "entry_points" (which we don't use.) If you know a better way, I'm all ears.
For now, it'll raise an exception if the import fails.
=> PR: Update update_fa5 command to rename internal font names during update

qtawesome/iconic_font.py
Fixes #113
Looks like icons are stored by reference in qt 5.12, so we need to keep
them alive somewhere.
Not sure though if the icon cache should reside in the library, or in user code.
The advantage of this PR is that it works without any changes to the user code.
=> PR: Keep icons alive in cache

qtawesome/iconic_font.py
Removed a number of deprecation warnings showing up in Python 3.8. This is based on the Spyder tests (and some additional eye-balling), so there may be more.
Gets rid of about 24000 warnings in the Python 3.8 Spyder tests...
(And a few trailing spaces automatically removed by Spyder...)
=> PR: Remove Python 3.8 deprecation warnings

example.py, qtawesome/iconic_font.py
I attempted to address #112. The added behavior mimic the helper CSS classes detailed on the material design icons usage page (https://cdn.materialdesignicons.com/3.0.39/)
Fixes #112.
=> PR: Add rotated, hflip, and vflip options

RELEASE.md
This adds more detailed instructions on how to do a release from the `0.x` branch.
@dalthviz, please review this one and merge if/when you consider it necessary.
=> PR: Update release instructions for the 0.x branch

qtawesome/tests/test_qtawesome.py
At least on openSUSE it requires python2 interpreter, but like this it calls the interpreter we are working with.
Supersedes #142
=> PR: Do not call python directly in tests

RELEASE.md
=> PR: Update RELEASE.md

qtawesome/__init__.py, qtawesome/iconic_font.py
- singleton instance does not check if it's fonts are still available in `QFontDatabase`
- `IconicFont` object also store loaded font ids
- added validation callback when `_instance()` is called to check if font ids are still in `QFontDatabase`
=> PR: Perform a font id validation

qtawesome/animation.py
If parent widget gets deleted timer automatically deleted to, instead timer tries to update already deleted widget.
=> PR: Timer should belong to parent widget

qtawesome/icon_browser.py
Hi,
This PR is for changing to "Ctrl+F" because PyQt6 doesn't support Modifier + Key.
With PyQt6,  `QtGui.QKeySequence(QtCore.Qt.CTRL + QtCore.Qt.Key_F)` in qtabrowser gives the following error:
```
File "/home/qtawesome/qtawesome/icon_browser.py", line 111, in __init__
QtGui.QKeySequence(QtCore.Qt.CTRL + QtCore.Qt.Key_F),
TypeError: unsupported operand type(s) for +: 'Modifier' and 'Key'
```
I tested qtabrowser on the following PyQt6 version.
```
PyQt6                      6.2.0
PyQt6-Qt6                  6.2.0
PyQt6-sip                  13.1.0
```
=> PR: Change to "Ctrl+F" because PyQt6 doesn't support Modifier + Key

qtawesome/icon_browser.py
Hi,
This PR makes new APIs priority use than removed or deprecated APIs
to solves the following DeprecationWarnings of qtabrowser with QT_API=pyside2 or QT_API=pyside6.
QT_API=pyside2
```
qtawesome/icon_browser.py:125: DeprecationWarning: QDesktopWidget.screenNumber(const QPoint & arg__1) const is deprecated
screen = desktop.screenNumber(desktop.cursor().pos())
qtawesome/qtawesome/icon_browser.py:126: DeprecationWarning: QDesktopWidget.screenGeometry(int screen) const is deprecated
centerPoint = desktop.screenGeometry(screen).center()
```
QT_API=pyside6
```
qtawesome/icon_browser.py:273: DeprecationWarning: 'exec_' will be removed in the future. Use 'exec' instead.
sys.exit(app.exec_())
```
* exec_ function is handled as discussed in https://github.com/spyder-ide/qtpy/issues/286
* …
=> PR: Try calling newer Qt methods first before falling back to deprecated/removed ones

setupbase.py
This PR resolves the following in https://github.com/spyder-ide/qtawesome/issues/189#issuecomment-988809501
>> Since the timestamp when the family is changed is embedded, the font checksum changes every time the command is executed, which is to be expected.
>
> * implement reproducing processing for changing family
By recalcTimestamp=False, "modified" timestamp field is preserved and same processing to change family returns same binary.
Also, recalcBBoxes=False and reorderTables=False are added to suppress processing that may change the table and content of font.
=> PR: Preserves timestamp, bboxes, and table order for faithful to original and reproducible font updating

qtawesome/__init__.py, qtawesome/iconic_font.py
Add examples and update the description according to the actually implemented `directory` kwarg handling
Fixes #195 
Also, jus in case, I added the `readthedocs` preview to the checks. So to check the changes done in the docs you can go to: https://qtawesomedocs--198.org.readthedocs.build/en/198/ (or check the `details` link in the `readthedocs` check)
=> PR: Update `load_font` documentation

UPDATE.md, qtawesome/__init__.py, qtawesome/iconic_font.py, setupbase.py
Fixes #196
```SYSTEM_FONTS``` has been removed in iconic_fonts.py because it is no longer needed.
I moved ```MD5_HASHES``` to \_\_init__.py and defined ```BUNDLED_FONTS``` in \_\_init__.py,
but I don't know "_" (underscore) should be prefixed in these variables  as internal use.
=> PR: Fix unexpected corruption check except for bundled fonts

setup.py, setupbase.py
This PR is preparing for removal of distutils in the future.
ref https://github.com/spyder-ide/qtawesome/pull/194#issuecomment-997031362
=> PR: Replace now deprecated distutils with setuptools

qtawesome/iconic_font.py
Hi @dalthviz.
This PR is to mitigate #39 to some extent.
As https://github.com/spyder-ide/qtawesome/pull/202#issuecomment-1031631561, the method using QRawFont and QPainterPath does not support all fonts supported by QFont.
So, I think the method is optional.
Even if QFont is used, by disabling font hinting, the tremulous spinning seems to be mitigated to some extent.
So, I think it is better that the font hinting is disabled as default when animation.
left: default (enable) hinting, right: disable hinting
=> PR: Disable font hinting to mitigate tremulous spinning to some extent

.github/workflows/linux-tests.yml, qtawesome/iconic_font.py, qtawesome/tests/test_qtawesome.py
* Fix CI for Linux
* Add way to copy and register font files to prevent error when using bundled fonts on Windows with the `prevent untrusted fonts` setting on.
Fixes #167 
Part of spyder-ide/spyder#18642
=> PR: Install bundled fonts for user on Windows and fix Linux CI

example.py, qtawesome/iconic_font.py
Maybe #39 can be fixed using QRawFont and draw PainterPath of Glyph.
Compared to QFont, QRawFont is available without registering to font database,
So this approach has
Pros:
* no tremulous spinning
* no family name collision (font patch is not required)
Cons:
* cannot support color-font (PainterPath of Glyph does not have color)
* cannot support font() API (this requires QFont registered to font database)
* I tests it on ubuntu only. I cannot check this approach works on other platform or not
If qtawesome switches QFont to QRawFont, font patch in the update_font script ( #194 ) may not be needed.
How do you think, @dalthviz  ?
Note: current code is example, so it needs refactoring, optimization, etc.
Edit:
Fixes #39
=> PR: Use QRawFont and draw PainterPath of Glyph for animation to prevent tremulous spinning icons

.github/workflows/linux-tests.yml, .github/workflows/macos-tests.yml, .github/workflows/windows-tests.yml, README.md, docs/environment.yml, qtawesome/iconic_font.py, requirements/environment.yml, requirements/environment_tests.yml
=> PR: Handle PySide2 not having `QtGui.QGlyphRun` and add tests jobs with PySide2

.github/workflows/linux-tests.yml, .github/workflows/macos-tests.yml, .github/workflows/windows-tests.yml, CONTRIBUTING.md, README.md, requirements/environment_tests_pyqt5.yml, requirements/environment_tests_pyside2.yml
=> PR: Add contributing guide and fix macOS tests

qtawesome/iconic_font.py
=> PR: Use currentThreadId to identify thread for PyQt bindings

.gitignore, qtawesome/iconic_font.py, requirements/environment_tests_pyside2.yml
=> PR: Change constants used to validate `PySide` installation and update `PySide2` test environment to use `QtPy`<2.0.0

.github/workflows/linux-tests.yml, .github/workflows/macos-tests.yml, .github/workflows/windows-tests.yml, README.md, requirements/environment.yml, requirements/environment_tests_pyqt5.yml, requirements/environment_tests_pyside2.yml
Using the codecov package can causes CI to fail with `pip` since the `codecov` package was removed from PyPI. The error from CI is the following:
```
ERROR: Could not find a version that satisfies the requirement codecov (from versions: none)
ERROR: No matching distribution found for codecov
```
Example Spyder CI run where this happens: https://github.com/spyder-ide/spyder/actions/runs/4681680400/jobs/8294575413?pr=20421#step:10:420
Remove codecov from requirements and use Codecov GitHub Action instead to upload coverage reports
=> PR: Remove usage of deprecated codecov package and move to GitHub Action variant

README.md, docs/source/usage.rst, example.py, qtawesome/__init__.py
I suggest adding a `size` keyword-only argument to the constructor of `IconWidget` to avoid extra `setIconSize` and `update` calls.
This way,
```python
icon_widget: qta.IconWidget = qta.IconWidget('mdi.web', color='blue')
icon_widget.setIconSize(QtCore.QSize(32, 32))
icon_widget.update()
```
turns into
```python
icon_widget: qta.IconWidget = qta.IconWidget('mdi.web', color='blue', size=QtCore.QSize(32, 32))
```
---
And I fixed a couple of typos in the docstring of the class.
=> PR: Provide icon size when creating an `IconWidget`

docs/environment.yml, docs/source/conf.py, readthedocs.yml
For more info about why the change is needed see: https://blog.readthedocs.com/migrate-configuration-v2/
=> PR: Update `readthedocs` config to version 2

README.md
Need to use GitHub URL to display README images over PyPI. Currently the images are not being loaded:
=> PR: Use GitHub raw content URL to display `README` images over package PyPI landing page

.github/workflows/linux-tests.yml, .github/workflows/macos-tests.yml, .github/workflows/windows-tests.yml, requirements/environment_tests_pyqt6.yml, requirements/environment_tests_pyside6.yml
Add tests for PyQt6 and PySide6.
Fix PySide2 test failing due to `pytest-qt` [dropped its support in 4.5.0](https://pytest-qt.readthedocs.io/en/4.5.0/changelog.html#id2).
For Qt5 bindings, Python 3.7 (EOL @ 2023-06-27) remains in the tests, for it mostly works still. I would bump the Python version up as soon as a failure occurs, without wasting time on a fix.
=> PR: Add Qt6 (PyQt6/PySide6) test jobs and fix PySide2 and `pytest-qt` support related failures

qtawesome/iconic_font.py, qtawesome/tests/test_qtawesome.py
Do not clear cache for the main app thread. When it terminates, the app is over anyway. The OS takes care of the memory. Otherwise, this causes a crash at the end of the `app.exec()` in Qt 6.8.2 to 6.9.0.
The PR proposes a test for the issue and a fix.
The PR might resolve spyder-ide/qtawesome#280.
=> PR: Do not clear the cache of `QRawFont` instances for the main app thread
